language: cpp
sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.7

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR-deps/usr/bin
  - pushd $TRAVIS_BUILD_DIR-deps/usr/bin
  - >
    if [ "$CXX" = "g++" ]; then
      ln -s /usr/bin/g++-4.7 g++
      ln -s /usr/bin/gcc-4.7 gcc
      ln -s /usr/bin/gcov-4.7 gcov
    fi
  - popd
  - export PATH="$TRAVIS_BUILD_DIR-deps/usr/bin:$PATH"

install:
  - gem install lcoveralls
  - pushd $TRAVIS_BUILD_DIR-deps
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - make PREFIX=$TRAVIS_BUILD_DIR-deps -C lcov-1.11/ install
  - popd

before_script:
  - gcov --version
  - lcov --version
  - lcoveralls --version
  - $CXX --version
  - mkdir -p $TRAVIS_BUILD_DIR-build

script:
  - pushd $TRAVIS_BUILD_DIR-build
  - cmake -DCMAKE_BUILD_TYPE=coverage -DLLHD_BUILD_DOC=OFF $TRAVIS_BUILD_DIR
  - make
  - if [ "$CXX" = "g++" ]; then make coverage-init; fi
  - make test
  - if [ "$CXX" = "g++" ]; then make coverage; fi
  - popd

after_success:
  - >
    if [ "$CXX" = "g++" ]; then
      lcoveralls --retry-count 5 $TRAVIS_BUILD_DIR-build/coverage.info
      bash <(curl -s https://codecov.io/bash) -f $TRAVIS_BUILD_DIR-build/coverage.info
    fi
