[package]
name = "llhd"
version = "0.10.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]
edition = "2018"

description = "A Low Level Hardware Description that acts as a foundation for building hardware design tools."
repository = "https://github.com/fabianschuiki/llhd"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
travis-ci = { repository = "fabianschuiki/llhd", branch = "master" }

[dependencies]
num = { version = "0.2", features = ["serde"] }
bitflags = "1"
clap = "2"
lalrpop-util = "0.16.3"
regex = "0.2.0"
log = { version = "0.4", features = ["release_max_level_info"] }
stderrlog = "0.4"
rayon = "1.2"
time = "0.1"
serde = { version = "1", features = ["derive", "rc"] }

[dev-dependencies]
indoc = "0.3"

[build-dependencies]
lalrpop = "0.16.3"
